# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackTheNorth' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HackTheNorth
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/MLVision'
  pod 'Firebase/MLVisionBarcodeModel'
  pod 'Firebase/Firestore'

  # Optionally, include the Swift extensions if you're using Swift.
  pod 'FirebaseFirestoreSwift'

  pod 'GoogleUtilities/AppDelegateSwizzler'
  pod 'GoogleUtilities/MethodSwizzler'
  pod 'GoogleUtilities/Network'
  pod 'GoogleUtilities/NSData+zlib'
  pod 'GoogleUtilities/AppDelegateSwizzler'
  pod 'GoogleUtilities/Environment'
  pod 'GoogleUtilities/Logger'
  pod 'GoogleUtilities/UserDefaults'
  pod 'GoogleUtilities/Reachability'



end
